### ISSUE TITLE
"Error starting quest - this will be retried next polling interval" infinite loop when adding 15+ heroes

### ISSUE THREAD

**Issue by cameronpants** [SansegoTek/DFKQuestRunner#14] opened 2021-12-11 00:49 UTC
Adding more then 15 heroIDs to the Fishing nonProfessionHeroes section of the config leads to a infinite loop of the error "Error starting quest - this will be retried next polling interval" when running the tool. This doesn't seem to happen for any other quest I've been running with the same amount of heroes.

https://i.gyazo.com/124509083626c18acd6fd65a8dea9f71.png

- I verified each individual heroID to make sure they were fully correct and correspond with the wallet being used (19 heroes total)
- I swapped the order of the heroIDs to make sure there wasn't a bugged hero somewhere in the order
- I removed each individual heroIDs until only 10-15 remained, only then did my quests start going through
- I verified all heroes apart of the nonProfessionHeroes section were not listed for sale or for hire in the tavern

I'm not entirely sure if it's just something on my end and how to go about troubleshooting/resolving it without any error logs, let me know if there's anything else I can do!

**Comment by SansegoTek** [comment] 2021-12-11 12:09
Thanks Cameron, great error report. I think the issue is that DFK will not allow more than 6 heroes on a quest at the same time, and the code today doesn't account for that - it will try to send as many as you have configured. Interesting that you say you can send 15 on a foraging quest though.

There's a fix for this in the pipeline, its the next highest priority, so it should be done soon.

**Comment by cameronpants** [comment] 2021-12-11 16:07
> Thanks Cameron, great error report. I think the issue is that DFK will not allow more than 6 heroes on a quest at the same time, and the code today doesn't account for that - it will try to send as many as you have configured. Interesting that you say you can send 15 on a foraging quest though.
There's a fix for this in the pipeline, its the next highest priority, so it should be done soon.

Awesome, thanks so much for the update, homie. Just wanted to verify the issue wasn't something on my end, really finding a lot of use out of this tool!

**Comment by cameronpants** [comment] 2021-12-11 16:07
> Thanks Cameron, great error report. I think the issue is that DFK will not allow more than 6 heroes on a quest at the same time, and the code today doesn't account for that - it will try to send as many as you have configured. Interesting that you say you can send 15 on a foraging quest though.
> 
> There's a fix for this in the pipeline, its the next highest priority, so it should be done soon.

**Comment by SansegoTek** [comment] 2021-12-14 11:18
The latest code solves this problem by batching the heroes into groups of no more than 6 to send them on quests

**Closed as completed by SansegoTek** 2021-12-14 11:18 UTC
